### ISSUE TITLE
M Cross Bug 2 glib Build Fail

### ISSUE THREAD

**Issue by tdineen** [mxe/mxe#799] opened 2015-08-26 19:36 UTC
Gentle People:

configure.ac:88: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.

   How and where do I define this macro and use m4_pattern_allow

make agg alure apu apr-util
[using autodetected 1 job(s)]
[build]     glib                 i686-w64-mingw32.static                                                   

Failed to build package glib for target i686-w64-mingw32.static!
------------------------------------------------------------
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
Makefile:412: recipe for target 'build-only-glib_i686-w64-mingw32.static' failed
make[1]: *** [build-only-glib_i686-w64-mingw32.static] Error 1
make[1]: Leaving directory '/home/tdineen/mxe_082015/mxe'
real	0m58.492s
user	0m35.956s
sys	0m8.296s
------------------------------------------------------------
[log]      /home/tdineen/mxe_082015/mxe/log/glib_i686-w64-mingw32.static

Makefile:412: recipe for target '/home/tdineen/mxe_082015/mxe/usr/i686-w64-mingw32.static/installed/glib' failed
make: *** [/home/tdineen/mxe_082015/mxe/usr/i686-w64-mingw32.static/installed/glib] Error 1
root@Debian-VBox1:/home/tdineen/mxe_082015/mxe# 
root@Debian-VBox1:/home/tdineen/mxe_082015/mxe# 
root@Debian-VBox1:/home/tdineen/mxe_082015/mxe# echo $GLIB_MAJOR_VERSION

root@Debian-VBox1:/home/tdineen/mxe_082015/mxe# 

libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4macros'.
libtoolize: copying file 'm4macros/libtool.m4'
libtoolize: copying file 'm4macros/ltoptions.m4'
libtoolize: copying file 'm4macros/ltsugar.m4'
libtoolize: copying file 'm4macros/ltversion.m4'
libtoolize: copying file 'm4macros/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
configure.ac:88: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
Makefile:412: recipe for target 'build-only-glib_i686-w64-mingw32.static' failed
make[1]: *** [build-only-glib_i686-w64-mingw32.static] Error 1
make[1]: Leaving directory '/home/tdineen/mxe_082015/mxe'

real    0m58.492s
user    0m35.956s
sys     0m8.296s

**Comment by starius** [comment] 2015-09-06 17:04
I can't reproduce this issue.
Maybe it is similar to the problem reported here:
https://blogs.oracle.com/mandy/entry/autoconf_weirdness

Can you tell which host do you use, please? Full log would be useful too. Please upload it to pastebin or http://gist.github.com/ because it is likely to be too large to post it here.

**Comment by dl5rcw** [comment] 2015-09-12 13:45
Same issue here running Debian Wheezy. All packages installed according to index.html via apt-get
output:
 [using autodetected 4 job(s)]
make[1]: Entering directory `/home/user/mxe'
uname -a
Linux automatix 2.6.32-5-amd64 #1 SMP Fri May 10 08:43:19 UTC 2013 x86_64 GNU/Linux
git show-branch --list --reflog=1
  [refs/heads/master@{0}] (88 minutes ago) clone: from https://github.com/mxe/mxe.git
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
Distributor ID: Debian
Description:    Debian GNU/Linux 7.9 (wheezy)
Release:        7.9
Codename:       wheezy
autoconf --version 2>/dev/null | head -1
autoconf (GNU Autoconf) 2.69
automake --version 2>/dev/null | head -1
automake (GNU automake) 1.14.1
rm -rf   '/home/user/mxe/tmp-glib-i686-w64-mingw32.shared'
mkdir -p '/home/user/mxe/tmp-glib-i686-w64-mingw32.shared'
cd '/home/user/mxe/tmp-glib-i686-w64-mingw32.shared' &&       xz -dc '/home/user/mxe/pkg/glib-2.42.1.tar.xz' | tar xf -
cd '/home/user/mxe/tmp-glib-i686-w64-mingw32.shared/glib-2.42.1'
(cd '/home/user/mxe/tmp-glib-i686-w64-mingw32.shared/glib-2.42.1' && patch -p1 -u) < ./src/glib-1-fixes.patch
patching file glib-2.0.pc.in
patching file gio/giomodule.c
patching file glib/glib-init.c
patching file configure.ac
patching file configure.ac
patching file gio-2.0.pc.in
patching file glib/gmain.c
patching file glib/gthread-win32.c
patching file Makefile.am
patching file autogen.sh
patching file configure.ac
patching file docs/Makefile.am
patching file docs/reference/Makefile.am
patching file docs/reference/gio/Makefile.am
patching file docs/reference/gio/gdbus-object-manager-example/Makefile.am
patching file docs/reference/glib/Makefile.am
patching file docs/reference/gobject/Makefile.am
patching file gio/tests/gdbus-object-manager-example/Makefile.am
cd '/home/user/mxe/tmp-glib-i686-w64-mingw32.shared/glib-2.42.1' && NOCONFIGURE=true ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4macros ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4macros'.
libtoolize: copying file `m4macros/libtool.m4'
libtoolize: copying file `m4macros/ltoptions.m4'
libtoolize: copying file `m4macros/ltsugar.m4'
libtoolize: copying file `m4macros/ltversion.m4'
libtoolize: copying file `m4macros/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
configure.ac:88: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
make[1]: *** [build-only-glib_i686-w64-mingw32.shared] Fehler 1
make[1]: Leaving directory `/home/user/mxe'

real    0m45.289s
user    0m43.767s
sys     0m1.484s

**Comment by tonytheodore** [comment] 2015-09-12 14:43
Could you:
* check that [all requirements are installed](http://mxe.cc/#requirements-debian)
* see if there's anything set in your env for `ACLOCAL_PATH`
* post the full log

**Comment by dl5rcw** [comment] 2015-09-12 16:46
All requirements are installed. Latest debian stable. Double checked.
   echo $ACLOCAL_PATH 
is empty. I executed in the same shall after the above posting failed.
Also reinstalled the requirements listed to check if something broke here - same behaviour.
The above output is the log from 
   cat /home/user/mxe/log/glib_i686-w64-mingw32.shared

**Comment by tonytheodore** [comment] 2015-09-12 16:55
Okay, could you try this:
```
make build-requirements && make glib
```
with any `-jx JOBS=y` options you normally use

**Comment by dl5rcw** [comment] 2015-09-12 17:57
JOBS autodetect = 4
settings.mk: MXE_TARGETS :=  i686-w64-mingw32.shared  x86_64-w64-mingw32.shared

 ------------ 
not it collides in coreutils:
[download]  coreutils
[build]     coreutils              x86_64-unknown-linux-gnu

Failed to build package coreutils for target x86_64-unknown-linux-gnu!
------------------------------------------------------------
checking whether mkfifo rejects trailing slashes... yes
checking whether mknod can create fifo without root privileges... configure: error: in `/home/user/mxe/tmp-coreutils-x86_64-unknown-linux-gnu/coreutils-8.23.build':
configure: error: you should not run configure as root (set FORCE_UNSAFE_CONFIGURE=1 in environment to bypass this check)
See `config.log' for more details
make[2]: *** [build-only-coreutils_x86_64-unknown-linux-gnu] Fehler 1
make[2]: Leaving directory `/home/user/mxe'
real    1m9.667s
user    0m59.848s
sys     0m17.473s

I did set the 
FORCE_UNSAFE_CONFIGURE=1
in the shell environment where I start the make command with the same result. 

A new issue?

**Comment by tonytheodore** [comment] 2015-09-12 18:10
You won't need coreutils, just libtool and deps. Try this instead (may already have built before the error):
```
make libtool MXE_TARGETS=`ext/config.guess`
```

**Comment by tonytheodore** [comment] 2015-09-13 05:21
> automake (GNU automake) 1.14.1

On a basic install, this is 1.11.6 (and builds successfully) - how did you install automake?

**Comment by dl5rcw** [comment] 2015-09-13 06:44
automake: 
   compiled from source in order to get sonarqube + jenkins sattisfied.

**Comment by dl5rcw** [comment] 2015-09-13 06:48
the command you posted did work. 
-> What does the option actually do to MXE? 
-> Can I place it to the settings.mk file?
-> How is it related to glib? 

As I was going for make qt5, I tried
   make qt5 MXE_TARGETS=`ext/config.guess`
--> with some tweaking, it seemed to work at the end. I did no qt5 project compilation yet with the new mxe environment.

I had a failure in gcrypt.h which I was able to fix:
 ----------------
In file included from ./src/libgcrypt-test.c:7:0:
/home/user/mxe/usr/x86_64-unknown-linux-gnu/include/gcrypt.h:509:32: error: comma at end of enumerator list [-Werror=edantic]
/home/user/mxe/usr/x86_64-unknown-linux-gnu/include/gcrypt.h:1346:29: error: comma at end of enumerator list [-Werror=edantic]
 ----------------
Worth another patch?

I currently try to reproduce in a clean environment to double check the results. This may take a while.

**Comment by tonytheodore** [comment] 2015-09-13 06:54
> compiled from source in order to get sonarqube + jenkins sattisfied

Did you install it to a standard location or somewhere custom and adjust $PATH? Based on earlier comment https://blogs.oracle.com/mandy/entry/autoconf_weirdness, I'd guess that it's something like the latter and the standard m4 macros (possibly pkg.m4) can't be found.

**Comment by tonytheodore** [comment] 2015-09-13 07:20
> -> What does the option actually do to MXE? 

It causes a native build of some common problematic tools.

> -> Can I place it to the settings.mk file?

No, it's mostly experimental and will be removed at some stage in the nearish future.

> -> How is it related to glib?

It isn't directly, just that glib happens to be one of the first packages that uses `autoreconf`. It appears to fix the build as `pkgconf` will install the required `pkg.m4` macro.

> make qt5 MXE_TARGETS=`ext/config.guess`

That will try a native build - too many things can go wrong with that.

> I currently try to reproduce in a clean environment to double check the results.

You could try something like:
```
env -i bash --noprofile --norc
```
to ensure you only use the default profile options. Otherwise, creating a new user might help.

**Comment by tonytheodore** [comment] 2015-09-13 08:01
@tdineen Have you manually installed any of the autotools (autoconf, automake, libtool... etc)?

**Comment by tonytheodore** [comment] 2015-09-13 11:22
@tdineen @dl5rcw Can you test a minimal case:
```sh
mkdir tmp-ac-check
cat <<EOF > tmp-ac-check/configure.ac
AC_INIT([mxe.cc], [1])
AC_PATH_PROG([AUTOCONF], [autoconf])
AC_PATH_PROG([AUTOMAKE], [automake])
AC_PATH_PROG([LIBTOOL], [libtool])
AC_PATH_PROG([PKG_CONFIG], [pkg-config])
PKG_PROG_PKG_CONFIG(0.28)
AC_OUTPUT
EOF
cd tmp-ac-check && autoreconf -fi && ./configure
```

Hopefully, it fails and we'll be able to catch it much earlier in the build.

**Comment by dl5rcw** [comment] 2015-09-13 12:13
I did a fresh checkout:
    git clone .....
executed to create the file:
    mkdir tmp-ad-check ........
executed the last line for the configure ocmmand:
    cd tmp-ac-check/ && autoreconf -fi && ./configure
output:
    checking for autoconf... /usr/bin/autoconf
    checking for automake... /usr/local/bin/automake
    checking for libtool... /usr/bin/libtool
    checking for pkg-config... /usr/bin/pkg-config
    ./configure: line 1828: syntax error near unexpected token `0.28'
    ./configure: line 1828: `PKG_PROG_PKG_CONFIG(0.28)'

**Comment by dl5rcw** [comment] 2015-09-13 12:13
echo $? returns 
   2

**Comment by tonytheodore** [comment] 2015-09-13 14:04
Thanks, that's perfect! I can replicate and fix it by moving the `pkg.m4` file around.

There's [a new basic sanity check of autotools](https://github.com/mxe/mxe/commit/989f09ca99a56cdb68f5f4b2dc65e9390b29289f) that should fail early and provide some pointers for investigation. If you pull that change, you should be able to re-test in a matter of seconds instead of building the entire toolchain up to `glib`.

In terms of getting the build working in that env, any of the following may work:
    * remove `/usr/local/bin` from $PATH
    * ensure `/usr/bin` precedes `/usr/local/bin` in $PATH so standard system tools are used
    * build pkg-config from source and install to `/usr/local` (as you did with automake)

**Comment by dl5rcw** [comment] 2015-09-16 17:55
I created a new user.

**Comment by dl5rcw** [comment] 2015-09-16 17:56
I created a new user and chose the 
    PATH=/usr/bin:$PATH 
way as you recommended.
    git checkout .... 
    make build-requirements

**Comment by tonytheodore** [comment] 2015-09-17 06:05
Okay, I shouldn't have mentioned `make build-requirements`, it solves a certain class of problems on FreeBSD and OSX, but causes more on Linux systems. Please ignore any reference to it or `MXE_TARGETS=ext/config.guess`.

One class of problems it tries to solve is mismatched versions of autotools, the [new sanity check for this](https://github.com/mxe/mxe/commit/989f09ca99a56cdb68f5f4b2dc65e9390b29289f) is much more robust across all systems.

With your new user and `$PATH` set correctly, `make qt5` should succeed or fail at some relevant package. It's known to build on a standard Wheezy so you shouldn't have further problems.

**Comment by dl5rcw** [comment] 2015-09-17 14:33
It is good that you mentioned it and I think it was necessary to narrow things down. Thanks for guiding me through the deeper dungeons of MXE. But I needed to reproduce our steps in order to get a clean process, understand the path we walked through and learn how things behave. Some jigsaw pieces have been missing until your last post.
This is now working and the issue can be closed. It compiles clean in a fresh environment as a user (do not compile as root).
 ----------------------
git clone https://github.com/mxe/mxe.git
cd mxe
git pull
PATH=/usr/bin:$PATH
echo $PATH
make qt5

**Comment by tonytheodore** [comment] 2015-09-17 17:32
Good to hear it's working for you now, and thanks for testing - a single confirmed fail is very useful! Kudos to @starius for finding [a path](https://blogs.oracle.com/mandy/entry/autoconf_weirdness) through [the haze](http://freecode.com/articles/stop-the-autoconf-insanity-why-we-need-a-new-build-system)

Hopefully the resolution is similar for @tdineen.

**Comment by tonytheodore** [comment] 2015-09-23 05:07
Closing for now, @tdineen please open a new issue if you still have problems - hopefully such things will be caught long before glib.

**Closed by tonytheodore** 2015-09-23 05:07 UTC
