### ISSUE TITLE
Failed to build package qt for target x86_64-w64-mingw32.shared

### ISSUE THREAD

**Issue by nschlia** [mxe/mxe#2810] opened 2022-04-08 12:18 UTC
Build of qt fails, even deleting everything and doing a fresh clone did not help. Build always breaks at the same target:
```
23:44:22 Failed to build package qt for target x86_64-w64-mingw32.shared!
23:44:22 ------------------------------------------------------------
23:44:22 make[3]: Leaving directory „/opt/mxe/tmp-qt-x86_64-w64-mingw32.shared/qt-everywhere-opensource-src-4.8.7/src/gui“ 
23:44:22 make[2]: *** [Makefile:459: sub-gui-make_default-ordered] Error 2
23:44:22 make[2]: Target „first“ not updated due to error.
23:44:22 make[2]: Verzeichnis „/opt/mxe/tmp-qt-x86_64-w64-mingw32.shared/qt-everywhere-opensource-src-4.8.7“ wird verlassen
23:44:22 make[1]: *** [Makefile:896: build-only-qt_x86_64-w64-mingw32.shared] Fehler 2
23:44:22 make[1]: Leaving directory  „/opt/mxe“
23:44:22 real	22m33,583s
23:44:22 user	35m19,419s
23:44:22 sys	5m42,696s
23:44:22 ------------------------------------------------------------
23:44:22 [log]      /opt/mxe/log/qt_x86_64-w64-mingw32.shared
23:44:22 
23:44:22 make: *** [Makefile:884: /opt/mxe/usr/x86_64-w64-mingw32.shared/installed/qt] Fehler 1
23:44:22 make: Targer „qt“ not updated due to errors
```
Whole log:
[qt_x86_64-w64-mingw32.shared.tar.gz](https://github.com/mxe/mxe/files/8451704/qt_x86_64-w64-mingw32.shared.tar.gz)

**Comment by brimmen** [comment] 2023-05-29 21:56
Hi Did you resolve this issue? I attempted on ubuntu 16 and debian bullseye, same output as yours. 
make MXE_TARGETS="i686-w64-mingw32.static" qt

[download]    qt-everywhere-opensource-src-4.8.7.tar.gz
MXE Warning! Downloading qt from backup.
[build]       qt                      i686-w64-mingw32.static

Failed to build package qt for target i686-w64-mingw32.static!
------------------------------------------------------------

**Comment by mabrand** [comment] 2024-03-21 16:06
Hope this is a duplicate of https://github.com/mxe/mxe/issues/3034, in which case it should be fixed now.

**Closed by mabrand** 2024-03-21 16:06 UTC
