### ISSUE TITLE
qt fails on i686-w64-mingw32.shared

### ISSUE THREAD

**Issue by noscript** [mxe/mxe#679] opened 2015-05-06 10:43 UTC
I upgraded from 1d4bf65 to latest e56d6e7 and now I get:

```
$ make MXE_TARGETS='i686-w64-mingw32.shared' qt
...
[build]    libgpg_error

Failed to build package libgpg_error!
------------------------------------------------------------
Makefile:563: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '~/mxe.git/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src'
Makefile:437: recipe for target 'build-only-libgpg_error_i686-w64-mingw32.shared' failed
make[1]: *** [build-only-libgpg_error_i686-w64-mingw32.shared] Error 2
make[1]: Leaving directory '~/mxe.git'
real	0m8.981s
user	0m8.492s
sys	0m1.060s
------------------------------------------------------------
[log]      ~/mxe.git/log/libgpg_error

Makefile:437: recipe for target '~/mxe.git/usr/i686-w64-mingw32.shared/installed/libgpg_error' failed
```

I tested on e56d6e7 with `i686-w64-mingw32.static` target, it builds fine. So only `shared` target is broken. I reverted back to 1d4bf65 and it builds fine again.

Here is `~/mxe.git/log/libgpg_error`:
```
...
/bin/bash ../libtool  --tag=CC   --mode=link i686-w64-mingw32.shared-gcc  -g -O2 -Wall -Wpointer-arith -Wno-psabi -no-undefined -export-symbols gpg-error.def  -XCClinker -static-libgcc -vers
libtool: link: if test "x`/bin/sed \"/^;/d; /^[ ]*$/d\" gpg-error.def | /bin/sed 1q`" = xEXPORTS; then cp gpg-error.def .libs/libgpg-error-0.dll.def; else echo EXPORTS > .libs/libgpg-error-0
libtool: link:  i686-w64-mingw32.shared-gcc -shared .libs/libgpg-error-0.dll.def  .libs/libgpg_error_la-w32-gettext.o .libs/libgpg_error_la-w32-lock.o .libs/libgpg_error_la-w32-thread.o .lib
.libs/libgpg_error_la-init.o: In function `real_init':
~/mxe.git/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src/init.c:79: undefined reference to `bindtextdomain'
.libs/libgpg_error_la-strsource.o: In function `gpg_strsource':
~/mxe.git/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src/strsource.c:36: undefined reference to `dgettext'
.libs/libgpg_error_la-strerror.o: In function `gpg_strerror':
~/mxe.git/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src/strerror.c:50: undefined reference to `dgettext'
.libs/libgpg_error_la-strerror.o: In function `gpg_strerror_r':
~/mxe.git/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src/strerror.c:161: undefined reference to `dgettext'
collect2: error: ld returned 1 exit status
Makefile:640: recipe for target 'libgpg-error.la' failed
make[3]: *** [libgpg-error.la] Error 1
make[3]: Leaving directory '~/mxe.git/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src'
Makefile:563: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '~/mxe.git/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src'
Makefile:437: recipe for target 'build-only-libgpg_error_i686-w64-mingw32.shared' failed
make[1]: *** [build-only-libgpg_error_i686-w64-mingw32.shared] Error 2
make[1]: Leaving directory '~/mxe.git'
```

**Comment by TimothyGu** [comment] 2015-05-06 14:35
Duplicate of #677.

**Closed by TimothyGu** 2015-05-06 14:35 UTC
