### ISSUE TITLE
Bugs in requirement lensfun with G

### ISSUE THREAD

**Issue by pabx06** [mxe/mxe#645] opened 2015-03-06 14:42 UTC
1)Needs to add the following in documentation #requirements:
```
sudo apt-get install autopoint
```

2)Comments out this line from lensfun's configure script when using GNU Make 4.0 :
```
tibs.check_program ("GNU Make", "make --version", ".*?([0-9\.]+).*", "3.81", True)
```
to avoid :
```
Checking for GNU Make >= 3.81                                    ...4.0 < 3.81, FAILED
```

**Comment by TimothyGu** [comment] 2015-05-01 18:37
Duplicate of #542. Fixed in master branch.

**Closed by TimothyGu** 2015-05-01 18:37 UTC
