### ISSUE TITLE
fontconfig build fails

### ISSUE THREAD

**Issue by lamaatje** [mxe/mxe#3041] opened 2024-01-26 12:42 UTC
I am new to building MXE and I trying to build as per instructions on focal (ubuntu 20.04). Everything went fine up to **fontconfig**. First issue I ran into was that a very new version of Autoconf is needed, configure.ac states 2.71. Installing this required version fixed it. Next issue is:
`Makefile.am: error: required file './README' not found.` There is a **README.md** in the package but the default automake flavor is GNU and is strict so e.g. adding in **configure.ac** the option  [foreign] in  AM_INIT_AUTOMAKE(...) would solve the problem. But I have no idea to do a quick local fix. Any tips here?

**Comment by mad-lad1** [comment] 2024-02-14 15:49
I am also facing this issue. Any workarounds or solutions?

**Comment by awonnacott** [comment] 2024-02-28 12:14
https://github.com/mxe/mxe/issues/3043 covers a related issue - I would recommend reverting to an older version of fontconfig

**Comment by mabrand** [comment] 2024-03-21 15:30
duplicate of https://github.com/mxe/mxe/issues/3043.
Should be fixed now.

**Closed by mabrand** 2024-03-21 15:30 UTC
