### ISSUE TITLE
Missing pkg-config file glut.pc causing OpenCV compilation to fail [workaround]

### ISSUE THREAD

**Issue by hekkup** [mxe/mxe#1433] opened 2016-07-10 19:09 UTC
Missing pkg-config file glut.pc is preventing OpenCV compilation. More specifically, compilation fails on libcaca which is a prerequisite for opencv Make target.

**Workaround:**
Copy this file
.../mxe/usr/i686-w64-mingw32.static/lib/pkgconfig/glu.pc
to
.../mxe/usr/i686-w64-mingw32.static/lib/pkgconfig/glut.pc

Edit the content of the file:
```
Name: glut
Version: 0
Description: OpenGL
Libs: -lglut32
```

If you are using other than i686-w64-mingw32.static target then you should figure out the last line.

After this, compilation proceeds normally (hope so).

**Comment by starius** [comment] 2016-07-10 20:02
Seems to be caused by https://github.com/mxe/mxe/pull/1429

**Comment by tehnick** [comment] 2016-07-10 21:08
@starius 
Nope. This problem was not added in #1429, but was fixed in it.

@hekkup 
Just try to build `opencv` from current master branch.

**Comment by starius** [comment] 2016-07-10 22:27
@tehnick, you are right. `libcaca` is fixed as of 2ee728cf99c0fe022e3fa9fddd0cfa41d79c8111

@hekkup, please check the build for latest commit.

I discovered other problem, caused by glut stuff: https://github.com/mxe/mxe/issues/1434

**Comment by tonytheodore** [comment] 2016-07-17 03:09
All downstream glut issues fixed by #1429 and #1441.

**Closed by tonytheodore** 2016-07-17 03:09 UTC
