### ISSUE TITLE
Failed to build package harfbuzz for target i686-w64-mingw32.static

### ISSUE THREAD

**Issue by KeterM** [mxe/mxe#2653] opened 2021-05-14 08:49 UTC
On Ubuntu 20.10, attempting to compile **qtbase**, using the source code obtained with git clone https://github.com/mxe/mxe.git, it fails to build harfbuzz.
The same with **make qt5**, and with **make MXE_TARGETS=x86_64-w64-mingw32.static qtbase** 

```
make qtbase
....

[build]       harfbuzz                i686-w64-mingw32.static

Failed to build package harfbuzz for target i686-w64-mingw32.static!
------------------------------------------------------------
make[3]: *** [Makefile:3387: install] Errore 2
make[3]: uscita dalla directory «/home/Keter/mxe/mxe/tmp-harfbuzz-i686-w64-mingw32.static/harfbuzz-2.8.1/src»
make[2]: *** [Makefile:524: install-recursive] Errore 1
make[2]: uscita dalla directory «/home/Keter/mxe/tmp-harfbuzz-i686-w64-mingw32.static/harfbuzz-2.8.1»
make[1]: *** [Makefile:870: build-only-harfbuzz_i686-w64-mingw32.static] Errore 2
make[1]: uscita dalla directory «/home/Keter/mxe/mxe»
real	0m23,000s
user	0m22,176s
sys	0m6,447s
------------------------------------------------------------
```
Here is the complete [log](https://gist.github.com/KeterM/8a8ca5fb13030db4bc32ccc31f55fca8)

Thank you for your attention

**Comment by tonytheodore** [comment] 2021-05-19 11:31
Very strange, there's an issue with `sed` that could be caused by autoconf.

Can you try skipping the regeneration with:
```
diff --git a/src/harfbuzz.mk b/src/harfbuzz.mk
index f3c66bd7..c79a720e 100644
--- a/src/harfbuzz.mk
+++ b/src/harfbuzz.mk
@@ -11,7 +11,7 @@ $(PKG)_DEPS     := cc cairo freetype-bootstrap glib icu4c

 define $(PKG)_BUILD
     # mman-win32 is only a partial implementation
-    cd '$(1)' && ./autogen.sh && ./configure \
+    cd '$(1)' && ./configure \
         $(MXE_CONFIGURE_OPTS) \
         ac_cv_header_sys_mman_h=no \
         CXXFLAGS='-std=c++11' \
```

**Comment by pekempy** [comment] 2021-06-04 08:00
I get a similar issue with python-setuptools when installing `make qtbase` or `make qt5` regardless of the MXE_TARGETS

```Failed to build package python-setuptools for target x86_64-pc-linux-gnu!
------------------------------------------------------------
    subprocess.check_call(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'setup.py', 'egg_info']' returned non-zero exit status 1.
make[1]: *** [Makefile:874: build-only-python-setuptools_x86_64-pc-linux-gnu] Error 1
make[1]: Leaving directory ' /home/pekempy/mxe'
real    0m5.573s
user    0m2.794s
sys     0m0.171s
------------------------------------------------------------
[log]      /home/pekempy/mxe/log/python-setuptools_x86_64-pc-linux-gnu

make: *** [Makefile:862: /home/pekempy4TB/.Programs/mxe/usr/x86_64-pc-linux-gnu/installed/python-setuptools] Error 1```

**Comment by positron96** [comment] 2021-09-23 04:07
Stmbled upon this as well. OS is Ubuntu xenial. Doing this in docker container.

**Comment by sskender** [comment] 2021-10-02 22:47
I also get this error when running `make qt5` and `make qttools`. OS is Ubuntu 18.04

**Comment by positron96** [comment] 2021-10-08 11:24
> Very strange, there's an issue with `sed` that could be caused by autoconf.
> 
> Can you try skipping the regeneration with:
> 
> ```
> diff --git a/src/harfbuzz.mk b/src/harfbuzz.mk
> index f3c66bd7..c79a720e 100644
> --- a/src/harfbuzz.mk
> +++ b/src/harfbuzz.mk
> @@ -11,7 +11,7 @@ $(PKG)_DEPS     := cc cairo freetype-bootstrap glib icu4c
> 
>  define $(PKG)_BUILD
>      # mman-win32 is only a partial implementation
> -    cd '$(1)' && ./autogen.sh && ./configure \
> +    cd '$(1)' && ./configure \
>          $(MXE_CONFIGURE_OPTS) \
>          ac_cv_header_sys_mman_h=no \
>          CXXFLAGS='-std=c++11' \
> ```

I've tried this and bash complains that there is no `configure` file. It seems that `autogen.sh` should be creating that.

I've dived into my logs and found out that in my case the cause of error was missing python3 binary. After installing python3 into ubuntu (docker image for ubuntu:xenial is missing one), **the build went fine**.

**Comment by sskender** [comment] 2021-10-20 07:48
> > Very strange, there's an issue with `sed` that could be caused by autoconf.
> > Can you try skipping the regeneration with:
> > ```
> > diff --git a/src/harfbuzz.mk b/src/harfbuzz.mk
> > index f3c66bd7..c79a720e 100644
> > --- a/src/harfbuzz.mk
> > +++ b/src/harfbuzz.mk
> > @@ -11,7 +11,7 @@ $(PKG)_DEPS     := cc cairo freetype-bootstrap glib icu4c
> > 
> >  define $(PKG)_BUILD
> >      # mman-win32 is only a partial implementation
> > -    cd '$(1)' && ./autogen.sh && ./configure \
> > +    cd '$(1)' && ./configure \
> >          $(MXE_CONFIGURE_OPTS) \
> >          ac_cv_header_sys_mman_h=no \
> >          CXXFLAGS='-std=c++11' \
> > ```
> 
> I've tried this and bash complains that there is no `configure` file. It seems that `autogen.sh` should be creating that.
> 
> I've dived into my logs and found out that in my case the cause of error was missing python3 binary. After installing python3 into ubuntu (docker image for ubuntu:xenial is missing one), **the build went fine**.

I had the same problem, can confirm that after installing python3 build passes.

**Comment by tonytheodore** [comment] 2022-04-24 13:15
fixed in https://github.com/mxe/mxe/commit/3b61050dabf8b3fb0fae9e373ebb88205758ced0

**Closed by tonytheodore** 2022-04-24 13:15 UTC
