### ISSUE TITLE
Download failed or wrong checksum of package libsigc++!

### ISSUE THREAD

**Issue by rgatti508** [mxe/mxe#2342] opened 2019-05-20 06:24 UTC
Hello,
Please help me to fix this issue while building mxe.
I have downloaded it from github and trying to run make.

fatal: Not a git repository (or any parent up to mount point /global/freeware)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[download]    libsigc++-2.4.0.tar.gz
MXE Warning! Downloading libsigc++ from backup.

Download failed or wrong checksum of package libsigc++!
------------------------------------------------------------
--2019-05-17 03:56:24--  http://d1yihgixbnrglp.cloudfront.net/libsigc%2B%2B%2D2%2E4%2E0%2Etar%2Egz_7593d5fa9187bbad7c6868dce375ce3079a805f3f1e74236143bceb15a37cd30
Resolving d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)... 99.84.231.190, 99.84.231.132, 99.84.231.225, ...
Connecting to d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)|99.84.231.190|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-17 03:56:24 ERROR 404: Not Found.
Download failed!
------------------------------------------------------------
[log]      /log/libsigc++-download

make: *** [download-only-libsigc++-2.4.0.tar.gz] Error 1

Thanks
Ravit

**Comment by damienrg** [comment] 2019-05-20 08:49
Please update `mxe` the error has been fixed in a58cf346b96b0f21bf35fd2cfcfce251836c9d2e.

**Comment by rgatti508** [comment] 2019-05-20 09:27
Can you please help me how to update.Please provide steps.
Thanks

**Comment by rgatti508** [comment] 2019-05-20 09:44
Hi damienrg,
Thanks for the help, I have updated mxe and building it again. It is taking too much time like more than 10 hours. Hope every thing goes well  this time.

**Comment by mabrand** [comment] 2019-05-28 11:43
I can reproduce the problem. It looks like libsigc++ 2.40 and other old releases of the package are not on the github releases page (any more). They are available from download.gnome.org, so I've added an explicit URL_2 to the .mk file as a workaround. Pushed as 5a76c0c22563e9c9f920b65f05aeffbfe1ac31ee.
Does anyone see a better way to handle this?

**Comment by tonytheodore** [comment] 2019-11-06 07:47
> The CMake build is not used very often by the libsigc++ developers, but it should work, and we would welcome improvements.

If CMake was fully encouraged, we could avoid using the release tarball and just use the normal github source archive feature.

`URL_2` is the best option if we don't wan't to `autoreconf`.

**Closed by tonytheodore** 2019-11-06 07:47 UTC
